# hugo server --themesDir ...

baseURL: https://mahasivipassana.com/
relativeURLs: true
title: Mahasi Vipassana Meditation Resources 
disableKinds: ["taxonomy", "taxonomyTerm"]
theme: book
# themesDir: ../..


# Book configuration
# (Optional) Set this to true if you use captial letters in file names
disablePathToLower: true
# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages
enableGitInfo: true

params:
  # (Optional, default true) Show or hide table of contents globally
  # You can also specify this parameter per page in front matter
  #BookShowToC: true

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  BookMenuBundle: /menu  

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection: docs
  
  # This value is duplicate of $link-color for making active link highlight in menu bundle mode
  # BookMenuBundleActiveLinkColor: \#004ed0

  # Include JS scripts in pages. Disabled by default.
  # - Keep side menu on same scroll position during navigation
  # BookEnableJS: true

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo: https://github.com/mahasivipassana/mahasivipassana

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # BookEditPath: edit/master/exampleSite/content
